language:
  - cpp

matrix:
  fast_finish: true
  include:
    # Linux GCC release build.
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: KSB_TARGET=LINUX KSB_TYPE=Release
    # Mac OS X Clang release build.
#    - os: osx
#      compiler: clang
#      sudo: required
#      env: KSB_TARGET=OSX KSB_TYPE=Release

cache:
  apt: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - cmake
      - libglfw3-dev

script:
  - if [[ "$KSB_TARGET" == "LINUX" ]]; then mkdir build && cd build; fi
  - if [[ "$KSB_TARGET" == "LINUX" ]]; cmake -DCMAKE_BUILD_TYPE=${KSB_TYPE:-Debug} ..; fi

notifications:
  email:
    recipients:
      - blazej.bucko@gmail.com
    on_success: change
    on_failure: always
