version: 2
jobs:
  build:
    docker:
      - image: blejzu/gcc-cmake-vulkan:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Debug build
          command: sh ./build.sh Debug
      - run:
          name: Test Debug
          command: sh ./test.sh Debug
      - run:
          name: Release build
          command: sh ./build.sh Release