version: 2
jobs:
  build:
    docker:
      - image: pmathia0/gcc-cmake-vulkan:latest
    steps:
      - checkout
      - run: apt-get install -y libglm-dev
      - run: mkdir build && cd build && cmake .. && make